Nini weather page
Tornike222/HW27Collaboration pull request #6
Opened 2024-05-18 11:45 UTC by Ninibardv

საბოლოო ვერსია არაა, კომენტარებში მიწერია რისი გასწორებაც მინდა და თქვენი აზრიც დამიწერეთ თუ კიდევ რამე შენიშვნა გაქვთ ან დამეთანხმეთ.

2024-05-18 12:19 UTC, mariamsreseli requested changes
ნინი კომენტარებად მიგიწერე რაღაცები

2024-05-18 12:19 UTC, mariamsreseli commented on NatureCollaboration/Scenes/WeatherPage/WeatherViewController.swift
> +        super.viewDidLoad()
ნინი view-ს background-ს ჯობია რო ფერი გაუწერო <3

2024-05-18 12:19 UTC, mariamsreseli commented on NatureCollaboration/Scenes/WeatherPage/WeatherViewController.swift
> +        getWeatherButton.addTarget(self, action: #selector(getWeatherButtonTapped), for: .touchUpInside) //selectors ar vikenebt
კარგი კომენტარია <3 addTarget-ის ნაცვლად addAction გამოიყენე

2024-05-18 12:19 UTC, mariamsreseli commented on NatureCollaboration/Scenes/WeatherPage/WeatherViewController.swift
> +    @objc private func getWeatherButtonTapped() {           //uiaction
good job Nini <3333

2024-05-18 12:19 UTC, sandrogelashvili requested changes
with great power comes great responsibility

2024-05-18 12:19 UTC, sandrogelashvili commented on NatureCollaboration/Scenes/WeatherPage/WeatherViewController.swift
> +class WeatherViewController: UIViewController, UITableViewDataSource, WeatherViewModelDelegate {
class -ები გახადე final

2024-05-18 12:19 UTC, sandrogelashvili commented on NatureCollaboration/Scenes/WeatherPage/WeatherViewController.swift
> +    // MARK: - Initializers
viewModel- ის ინიზიალიზაცია და viewDidLoad მოაქციე ერთი lifecycle ის ქვეშ. ეს ინიციზიალიზება ჩაიტანე დაბლა viewdidload თან

2024-05-18 12:19 UTC, sandrogelashvili commented on NatureCollaboration/Scenes/WeatherPage/WeatherViewController.swift
> +    private func setupViews() {
setUpUI - დაარქვი ამ ფუნქციას.

2024-05-18 12:20 UTC, Salomeeli commented on NatureCollaboration/Scenes/WeatherPage/Model.swift
> +struct WeatherForecast: Codable {
codable ყველგან decodable გახადე, თუ არსად არ იყენებ.

2024-05-18 12:20 UTC, Salomeeli commented on NatureCollaboration/Scenes/WeatherPage/WeatherViewController.swift
> +class WeatherViewController: UIViewController, UITableViewDataSource, WeatherViewModelDelegate {
UITableViewDataSource, WeatherViewModelDelegate გაიტანე ცალ-ცალე ექსთებნშენებად

2024-05-18 12:20 UTC, Salomeeli commented on NatureCollaboration/Scenes/WeatherPage/WeatherViewController.swift
> +        textField.translatesAutoresizingMaskIntoConstraints = false
translatesAutoresizingMaskIntoConstraints customtextfield-ისთვის დეფოლტად ფოლსია ისედაც...

2024-05-18 12:20 UTC, Salomeeli commented on NatureCollaboration/Scenes/WeatherPage/WeatherViewController.swift
> +        textField.translatesAutoresizingMaskIntoConstraints = false
აქაც

2024-05-18 12:20 UTC, Tornike222 requested changes
კომენტარები მიგიწერე და გადაჩექე (ეს დავითის და ბექას დასანახად თორე ქოლზე ვართ თან :დდდდდდ)

2024-05-18 12:20 UTC, Tornike222 commented on NatureCollaboration/Scenes/WeatherPage/WeatherViewController.swift
> +        present(alert, animated: true, completion: nil)    // tu arascoria daaclearos fildebi
კი აქ თუ მოვიდა და ეს ერორი თუ ამოუგდო, ოკ ბათონზე დაჭერისას დააქლეაროს Long Lat ჩასაწერი ტექსტფილდები

2024-05-18 12:20 UTC, Tornike222 commented on NatureCollaboration/Scenes/WeatherPage/WeatherViewController.swift
> +        let backgroundImageView: UIImageView = {
ეს გაიტანე ზემოთ სხვა UI Component ებთან ერთად

2024-05-18 12:20 UTC, Tornike222 commented on NatureCollaboration/Scenes/WeatherPage/WeatherViewController.swift
> +        view.addSubview(latitudeLabel)
თითოეული საბვიუს დამატებისთვის და კონსტრეინტების დადებისთვის გააკეთე ცალკე ფუნქცია, რომელსაც შემდგომში setupUI ფუნქციაში გამოიძახებ.

2024-05-18 12:20 UTC, Tornike222 commented on NatureCollaboration/Scenes/WeatherPage/WeatherViewController.swift
> +        getWeatherButton.addTarget(self, action: #selector(getWeatherButtonTapped), for: .touchUpInside) //selectors ar vikenebt
button.addAction UIAction გამოიყენე აქ

2024-05-18 12:20 UTC, Tornike222 commented on NatureCollaboration/Scenes/WeatherPage/WeatherViewModel.swift
> +    func unwrapData(latitude: String?, longitude: String?) {
ანვრაპის გარდა სხვა საქმესაც აკეთებს ეს ფუნქცია, შესაბამისად

2024-05-18 13:21 UTC, Ninibardv commented on NatureCollaboration/Scenes/WeatherPage/WeatherViewController.swift
> +    @objc private func getWeatherButtonTapped() {           //uiaction
thanks :*

2024-05-18 13:23 UTC, Ninibardv commented on NatureCollaboration/Scenes/WeatherPage/WeatherViewController.swift
> +        textField.translatesAutoresizingMaskIntoConstraints = false
- [ ]

2024-05-18 13:45 UTC, Ninibardv commented on NatureCollaboration/Scenes/WeatherPage/WeatherViewController.swift
> +        super.viewDidLoad()
done <3

2024-05-18 13:46 UTC, Ninibardv commented on NatureCollaboration/Scenes/WeatherPage/WeatherViewController.swift
> +        getWeatherButton.addTarget(self, action: #selector(getWeatherButtonTapped), for: .touchUpInside) //selectors ar vikenebt
done <3

2024-05-18 13:47 UTC, Ninibardv commented on NatureCollaboration/Scenes/WeatherPage/WeatherViewController.swift
> +    private func setupViews() {
done

2024-05-18 18:28 UTC, Ninibardv commented on NatureCollaboration/Scenes/WeatherPage/WeatherViewModel.swift
> +    func unwrapData(latitude: String?, longitude: String?) {
რა დავარქვა აბა მითხარი და დავარქმევ !!!

2024-05-19 00:07 UTC, Tornike222 commented on NatureCollaboration/Scenes/WeatherPage/WeatherViewController.swift
> +    init(viewModel: WeatherViewModel){
Nice 😊

2024-05-19 00:09 UTC, Tornike222 approved these changes
კარგია ყოჩაღ🚀

2024-05-19 00:10 UTC, sandrogelashvili approved these changes
kopwia kodia

2024-05-19 00:14 UTC, mariamsreseli approved these changes
kargi xar nini <3

2024-05-19 00:14 UTC, merged

2024-05-19 05:16 UTC, Tornike222 commented on NatureCollaboration/Scenes/WeatherPage/WeatherViewModel.swift
> +    func unwrapData(latitude: String?, longitude: String?) {
unwrapAndFetchWeatherData